name: build_release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_output:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - name: Install dependencies
      run: pip install PyYAML
    - name: execute py script # run file
      run: |
        python JsonOutput/JsonOutput.py
        python SigmaOutput/SigmaOutput.py
        zip -r ./ci-output/sigma_rules.zip ./ci-output/sigma
    - name: create release
      run: |
        gh release create $TITLE ./ci-output/rmms.json ./ci-output/sigma_rules.zip -F CHANGELOG.md
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TITLE: ${{ github.ref_name }}
